### ISSUE TITLE
Using massif plugin ("org.eclipse.incquery") in own environment

### ISSUE THREAD

**Issue by piyenghar** [FTSRG/massif#41]
Hello,

We have been using Massif plugins in our enviornment. Our last usage was in July-August (approx.). Again, we have tried to use the enviornment we have set up using Massif plug-ins, seems like there has been update (Incquery runtime). We get the following error. Any pointers to solving this would be appreciated.

java.lang.NoClassDefFoundError: org/eclipse/incquery/runtime/matchers/context/IPatternMatcherRuntimeContext
	at org.eclipse.incquery.runtime.emf.EMFScope.createEngineContext(EMFScope.java:133)
	at org.eclipse.incquery.runtime.internal.apiimpl.IncQueryEngineImpl.<init>(IncQueryEngineImpl.java:131)
	at org.eclipse.incquery.runtime.api.AdvancedIncQueryEngine.createUnmanagedEngine(AdvancedIncQueryEngine.java:200)
	at hu.bme.mit.massif.simulink.api.util.bus.BusSignalMapper.<init>(BusSignalMapper.java:56)
	at hu.bme.mit.massif.simulink.api.Importer.createBusSignalMappings(Importer.java:607)
	at hu.bme.mit.massif.simulink.api.Importer.traverseAndCreateEMFModel(Importer.java:590)

I have attached the target platform state (runtime version info.) as a screenshot from eclipse.

Cheers
Padma
![incquery_error](https://cloud.githubusercontent.com/assets/5106742/10998143/50db142a-8493-11e5-9ba5-cc2a9e11a31b.png)

**Comment by abelhegedus** [comment]
Yes, you will need EMF-IncQuery 1.0.x to use the current master version of Massif.
In addition, EMF-IncQuery 1.1.0 will be released on Nov 12th, 2015, and after that, Massif master will use that version. We will create a release before updating the dependencies.

**Comment by abelhegedus** [comment]
See https://github.com/FTSRG/massif/wiki/UserGuide#installation "Current master works with the latest release of EMF-IncQuery"

**Comment by abelhegedus** [comment]
On the contrary, if you wish to keep on using your current version of Massif (which requires EMF-IncQuery 0.9.1), make sure you don't install EMF-IncQuery 1.0.x (I can see that the databinding plugin is 1.0.1).
